
insert into MEDIA_TYPE(type)
values ('music'),
       ('video'),
       ('podcast');

insert into GENRES (genre_name)
values ('Black Metal'),
       ('Crust Punk'),
       ('Thrash Metal');

insert into ARTISTS(genre_id, artist_name)
values  (1,'Batushka'),
        (1,'Grima'),
        (2, 'Wolfbrigade'),
        (3, 'Metallica');

insert into albums(artist_id, album_title)
VALUES (1, 'Litourgiya'),
       (2, 'Rotting Garden'),
       (2, 'Frostbitten'),
       (3, 'Run With the Hunted'),
       (4, 'Kill em all');

insert into tracks(artist_id, genre_id, media_type_id, media_name,release_date)
VALUES (1, 1, 1, 'Yekteniya 1', '4-12-2015'),
       (1, 1, 1,'Yekteniya 2', '4-12-2015'),
       (1, 1, 1,'Yekteniya 3', '4-12-2015'),
       (1, 1, 1,'Yekteniya 4', '4-12-2015'),
       (1, 1, 1,'Yekteniya 5', '4-12-2015'),
       (1, 1, 1,'Yekteniya 6', '4-12-2015'),
       (1, 1, 1,'Yekteniya 7', '4-12-2015'),
       (1, 1, 1,'Yekteniya 8', '4-12-2015'),
       (2, 1, 1, 'Cedar and Owls', '22-01-2021'),
       (2, 1, 1, 'Mourning Comes at Sunset', '22-01-2021'),
       (2, 1, 1, 'At the Foot of the Red Mountains', '22-01-2021'),
       (2, 1, 1, 'Old Oak', '22-01-2021'),
       (2, 1, 1, 'Rotting Garden', '22-01-2021'),
       (2, 1, 1, 'Grom', '22-01-2021'),
       (2, 1, 1, 'Devotion to Lord', '22-01-2021'),
       (2, 1, 1, 'Gloomy Heart of the Coldest Land', '29-7-2022'),
       (2, 1, 1, 'Giants Eternal Sleep', '29-7-2022'),
       (2, 1, 1, 'Into the Twilight', '29-7-2022'),
       (2, 1, 1, 'Hunger God', '29-7-2022'),
       (2, 1, 1, 'Moonspell and Grief', '29-7-2022'),
       (2, 1, 1, 'Winter Morning Tower', '29-7-2022'),
       (2, 1, 1, 'Mana', '29-7-2022'),
       (3, 2, 1, 'Nomad Pack', '28-4-2017'),
       (3, 2, 1, 'Warsaw Speedwolf', '28-4-2017'),
       (3, 2, 1, 'Lucid Monomania', '28-4-2017'),
       (3, 2, 1, 'No Reward', '28-4-2017'),
       (3, 2, 1, 'Kallocain', '28-4-2017'),
       (3, 2, 1, 'Return to None', '28-4-2017'),
       (3, 2, 1, 'War on Rules', '28-4-2017'),
       (3, 2, 1, 'Feral Blood', '28-4-2017'),
       (3, 2, 1, 'Under the Bell', '28-4-2017'),
       (3, 2, 1, 'Dead Cold', '28-4-2017');

// (artist_id integer, genre_id integer, id integer generated by default as identity, media_type_id integer, media_name varchar(255), release_date varchar(255),



