
insert into MEDIA_TYPE(type)
values ('music'),
       ('video'),
       ('podcast');

insert into GENRES (genre_name)
values ('Black Metal'),
       ('Crust Punk'),
       ('Thrash Metal');

insert into ARTISTS(genre_id, artist_name)
values  (1,'Batushka'),
        (1,'Grima'),
        (2, 'Wolfbrigade'),
        (3, 'Metallica');

insert into albums(artist_id, album_title)
VALUES (1, 'Litourgiya'),
       (2, 'Rotting Garden'),
       (2, 'Frostbitten'),
       (3, 'Run With the Hunted');

insert into albums(artist_id, album_title, release_date)
VALUES (4, 'Kill em All','25-07-1983'),
       (4, 'Ride the Lightning ','27-07-1984'),
       (4, 'Master of Puppets', '03-03-1986');

-- RELEASE DATE MUST BE [ 'dd-MM-yyyy' ] SINGLE DIGITS MUST HAVE A ZERO BEFORE THEM <---------------

insert into tracks(artist_id, genre_id, media_type_id, media_name, release_date, album_id, url)
VALUES (1, 1, 1, 'Yekteniya 1', '04-12-2015', 1,'https://youtu.be/XCMNqKuuFC4?si=t3vyUAjqayR4p8gh'),
       (1, 1, 1,'Yekteniya 2', '04-12-2015', 1, 'https://youtu.be/XCMNqKuuFC4?si=t3vyUAjqayR4p8gh'),
       (1, 1, 1,'Yekteniya 3', '04-12-2015', 1, 'https://youtu.be/XCMNqKuuFC4?si=t3vyUAjqayR4p8gh'),
       (1, 1, 1,'Yekteniya 4', '04-12-2015', 1, 'https://youtu.be/XCMNqKuuFC4?si=t3vyUAjqayR4p8gh'),
       (1, 1, 1,'Yekteniya 5', '04-12-2015', 1, 'https://youtu.be/XCMNqKuuFC4?si=t3vyUAjqayR4p8gh'),
       (1, 1, 1,'Yekteniya 6', '04-12-2015', 1, 'https://youtu.be/XCMNqKuuFC4?si=t3vyUAjqayR4p8gh'),
       (1, 1, 1,'Yekteniya 7', '04-12-2015', 1, 'https://youtu.be/XCMNqKuuFC4?si=t3vyUAjqayR4p8gh'),
       (1, 1, 1,'Yekteniya 8', '04-12-2015', 1, 'https://youtu.be/XCMNqKuuFC4?si=t3vyUAjqayR4p8gh');
/*
insert into tracks(artist_id, genre_id, media_type_id, media_name, release_date, album_id, url)
VALUES (2, 1, 1, 'Cedar and Owls', '22-01-2021',2),
       (2, 1, 1, 'Mourning Comes at Sunset', '22-01-2021',2),
       (2, 1, 1, 'At the Foot of the Red Mountains', '22-01-2021',2),
       (2, 1, 1, 'Old Oak', '22-01-2021',2),
       (2, 1, 1, 'Rotting Garden', '22-01-2021',2),
       (2, 1, 1, 'Grom', '22-01-2021',2),
       (2, 1, 1, 'Devotion to Lord', '22-01-2021',2),
       (2, 1, 1, 'Gloomy Heart of the Coldest Land', '29-07-2022',2),
       (2, 1, 1, 'Giants Eternal Sleep', '29-07-2022',2),
       (2, 1, 1, 'Into the Twilight', '29-07-2022',2),
       (2, 1, 1, 'Hunger God', '29-07-2022',2),
       (2, 1, 1, 'Moonspell and Grief', '29-07-2022',2),
       (2, 1, 1, 'Winter Morning Tower', '29-07-2022',2),
       (2, 1, 1, 'Mana', '29-07-2022',2);

insert into tracks(artist_id, genre_id, media_type_id, media_name, release_date, album_id, url)
VALUES  (3, 2, 1, 'Nomad Pack', '28-04-2017',3),
        (3, 2, 1, 'Warsaw Speedwolf', '28-04-2017',3),
        (3, 2, 1, 'Lucid Monomania', '28-04-2017',3),
        (3, 2, 1, 'No Reward', '28-04-2017',3),
        (3, 2, 1, 'Kallocain', '28-04-2017',3),
        (3, 2, 1, 'Return to None', '28-04-2017',3),
        (3, 2, 1, 'War on Rules', '28-04-2017',3),
        (3, 2, 1, 'Feral Blood', '28-04-2017',3),
        (3, 2, 1, 'Under the Bell', '28-04-2017',3),
        (3, 2, 1, 'Dead Cold', '28-04-2017',3);

insert into tracks(artist_id, genre_id, media_type_id, media_name, release_date, album_id, url)
VALUES (4, 3, 1, 'Hit the Lights', '25-07-1983', 5),
       (4, 3, 1,'The Four Horsemen', '25-07-1983', 5),
       (4, 3, 1,'Motorbreath', '25-07-1983', 5),
       (4, 3, 1,'Jump in the Fire', '25-07-1983', 5),
       (4, 3, 1,'(Anesthesia)-Pulling Teeth', '25-07-1983', 5),
       (4, 3, 1,'Whiplash', '25-07-1983', 5),
       (4, 3, 1,'Phantom Lord', '25-07-1983', 5),
       (4, 3, 1,'No Remorse', '25-07-1983', 5),
       (4, 3, 1,'Seek & Destroy', '25-07-1983', 5),
       (4, 3, 1,'Metal Militia', '25-07-1983', 5);

insert into tracks(artist_id, genre_id, media_type_id, media_name, release_date, album_id, url)
VALUES (4, 3, 1, 'Fight Fire With Fire', '27-07-1984', 6),
       (4, 3, 1,'Ride The Lightning', '27-07-1984', 6),
       (4, 3, 1,'For Whom The Bells Toll', '27-07-1984', 6),
       (4, 3, 1,'Fade To Black', '27-07-1984', 6),
       (4, 3, 1,'Trapped Under Ice', '27-07-1984', 6),
       (4, 3, 1,'Escape ', '27-07-1984', 6),
       (4, 3, 1,'Creeping Death', '27-07-1984', 6),
       (4, 3, 1,'Call Of Ktulu', '27-07-1984', 6);

-- (artist_id integer, genre_id integer, id integer generated by default as identity, media_type_id integer, media_name varchar(255), release_date varchar(255),



 */

